# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    # platform: linux/x86_64 # M1 Macの場合だけ必要。それ以外の環境では削除する
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    env_file:
      - mysql.env
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin

  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    environment:
      TZ: Asia/Tokyo
